name: hackeros_connect_desktop
description: HackerOS Connect Desktop - Cross-device connectivity inspired by KDE Connect.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  multicast_dns: ^0.3.2  # Zmienione na to dla discovery
  flutter_local_notifications: ^17.2.3
  clipboard: ^0.1.3
  file_picker: ^8.1.2
  device_info_plus: ^10.1.2
  battery_plus: ^6.0.1
  shared_preferences: ^2.3.2
  particles_flutter: ^0.1.4
  path: ^1.9.0
  process_run: ^0.14.2
  http: ^1.2.2
  path_provider: ^2.1.4  # Dodane dla temp files jeÅ›li potrzeba

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/HackerOS-Connect.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/HackerOS-Connect.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/HackerOS-Connect.png"
  macos:
    generate: true
    image_path: "assets/images/HackerOS-Connect.png"
  linux:
    generate: true
    image_path: "assets/images/HackerOS-Connect.png"
